2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_setup.py:_flush():79] Configure stats pid to 64376
2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_setup.py:_flush():79] Loading settings from /home/samkit/.config/wandb/settings
2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_setup.py:_flush():79] Loading settings from /home/samkit/Documents/smai/smai-m24-assignments-samkit-2512j/assignments/3/wandb/settings
2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'project': 'Classifier_hyperparametrs', 'entity': 'samkit_25j_', 'root_dir': '/home/samkit/Documents/smai/smai-m24-assignments-samkit-2512j/assignments/3', 'sweep_id': 'siix3xsh', 'run_id': 'rhh8896h', 'sweep_param_path': '/home/samkit/Documents/smai/smai-m24-assignments-samkit-2512j/assignments/3/wandb/sweep-siix3xsh/config-rhh8896h.yaml'}
2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'assignments/3/sweep_wandb.py', 'program_abspath': '/home/samkit/Documents/smai/smai-m24-assignments-samkit-2512j/assignments/3/sweep_wandb.py', 'program': 'sweep_wandb.py'}
2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_init.py:_log_setup():532] Logging user logs to /home/samkit/Documents/smai/smai-m24-assignments-samkit-2512j/assignments/3/wandb/run-20241013_182313-rhh8896h/logs/debug.log
2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_init.py:_log_setup():533] Logging internal logs to /home/samkit/Documents/smai/smai-m24-assignments-samkit-2512j/assignments/3/wandb/run-20241013_182313-rhh8896h/logs/debug-internal.log
2024-10-13 18:23:13,614 INFO    Thread-2  :64376 [wandb_init.py:init():617] calling init triggers
2024-10-13 18:23:13,615 INFO    Thread-2  :64376 [wandb_init.py:init():624] wandb.init called with sweep_config: {'activations': 'tanh', 'batch_size': 256, 'early_stopping': True, 'epochs': 1000, 'hidden_layers': [128, 64], 'learning_rate': 0.017491933416624732, 'loss_func': 'cce', 'model': 'classifier', 'optimizer': 'batch'}
config: {'hidden_layers': [32, 16], 'learning_rate': 0.001, 'batch_size': 64, 'epochs': 100, 'optimizer': 'mini-batch', 'loss_func': 'cce', 'activation': <class 'models.MLP.activations.tanh'>, 'model': 'classifier', 'early_stopping': True}
2024-10-13 18:23:13,615 INFO    Thread-2  :64376 [wandb_init.py:init():667] starting backend
2024-10-13 18:23:13,615 INFO    Thread-2  :64376 [wandb_init.py:init():671] sending inform_init request
2024-10-13 18:23:13,619 INFO    Thread-2  :64376 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-13 18:23:13,620 INFO    Thread-2  :64376 [wandb_init.py:init():684] backend started and connected
2024-10-13 18:23:13,627 INFO    Thread-2  :64376 [wandb_run.py:_config_callback():1394] config_cb None None {'activations': 'tanh', 'batch_size': 256, 'early_stopping': True, 'epochs': 1000, 'hidden_layers': [128, 64], 'learning_rate': 0.017491933416624732, 'loss_func': 'cce', 'model': 'classifier', 'optimizer': 'batch'}
2024-10-13 18:23:13,629 INFO    Thread-2  :64376 [wandb_init.py:init():779] updated telemetry
2024-10-13 18:23:13,639 INFO    Thread-2  :64376 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-13 18:23:13,980 INFO    Thread-2  :64376 [wandb_init.py:init():863] starting run threads in backend
2024-10-13 18:23:14,042 INFO    Thread-2  :64376 [wandb_run.py:_console_start():2465] atexit reg
2024-10-13 18:23:14,042 INFO    Thread-2  :64376 [wandb_run.py:_redirect():2313] redirect: wrap_raw
2024-10-13 18:23:14,042 INFO    Thread-2  :64376 [wandb_run.py:_redirect():2378] Wrapping output streams.
2024-10-13 18:23:14,042 INFO    Thread-2  :64376 [wandb_run.py:_redirect():2403] Redirects installed.
2024-10-13 18:23:14,043 INFO    Thread-2  :64376 [wandb_init.py:init():907] run started, returning control to user process
2024-10-13 18:23:14,043 INFO    Thread-2  :64376 [wandb_run.py:_finish():2164] finishing run samkit_25j_/Classifier_hyperparametrs/rhh8896h
2024-10-13 18:23:14,044 INFO    Thread-2  :64376 [wandb_run.py:_atexit_cleanup():2428] got exitcode: 1
2024-10-13 18:23:14,044 INFO    Thread-2  :64376 [wandb_run.py:_restore():2410] restore
2024-10-13 18:23:14,044 INFO    Thread-2  :64376 [wandb_run.py:_restore():2416] restore done
2024-10-13 18:23:18,047 INFO    Thread-2  :64376 [wandb_run.py:_restore():2410] restore
2024-10-13 18:23:18,047 INFO    Thread-2  :64376 [wandb_run.py:_restore():2416] restore done
2024-10-13 18:23:18,047 ERROR   Thread-2  :64376 [wandb_run.py:_atexit_cleanup():2449] Problem finishing run
Traceback (most recent call last):
  File "sweep_wandb.py", line 74, in run
    model = MLPW(
TypeError: __init__() got an unexpected keyword argument 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/samkit/anaconda3/envs/normal/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2440, in _atexit_cleanup
    self._on_finish()
  File "/home/samkit/anaconda3/envs/normal/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2682, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/home/samkit/anaconda3/envs/normal/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/samkit/anaconda3/envs/normal/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/samkit/anaconda3/envs/normal/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/samkit/anaconda3/envs/normal/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/samkit/anaconda3/envs/normal/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
Exception
2024-10-13 18:23:18,060 WARNING MsgRouterThr:64376 [router.py:message_loop():77] message_loop has been closed
